services:
  postgres:
    container_name: todolist-db
    image: postgres
    environment:
      POSTGRES_USER: nzangi
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todolist
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nzangi"]
      interval: 10s
      timeout: 5s
      retries: 5


    networks:
      todolist-net:
    restart: unless-stopped


  todolist-app:
    container_name: todolist-app
    image: todolist:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todolist-db:5432/todolist
      SPRING_DATASOURCE_USERNAME: nzangi
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - 8222:8788
    networks:
      - todolist-net

    depends_on:
      - postgres
#    entrypoint: ["sh", "-c", "wait-for-it.sh todolist-db:5432 -- ./start-app.sh"]:


networks:
  todolist-net:
    driver: bridge
volumes:
  postgres:
