spring:
  application:
    name: todolist-docker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://todolist-db:5431/todolist
    username: nzangi
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8788
