spring:
  profiles:
    active: dev
  application:
    name: todolist-docker

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/todolist
    username: nzangi
    password: root
    hikari:
      maximum-pool-size: 20



server:
  port: 8788

